config/routes.rb
Rails.application.routes.draw do
  get 'rewards/new'
  get 'rewards/create'
  get 'achievements/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "pages#welcome"
  get 'pages/home', to: 'pages#home', as: 'home'
  get '/pages/welcome', to: 'pages#welcome', as: 'welcome'
  get '/achievements', to: 'achievements#index', as: 'achievements'
  get '/pages/profile', to: 'pages#profile', as: 'profile'
  get '/pages/profil', to: 'pages#profil', as: 'profil'
  get '/redirection', to: 'pages#redirection', as: 'redirection'
  get '/pages/impact', to: 'pages#impact', as: 'impact'
  get '/pages/convertisseur', to: 'pages#convertisseur', as: 'convertisseur'

  resources :actions, only: [:index, :show] do
    post 'add_to_challenges', on: :member
    resources :user_challenges, only: [:create]
  end

  resources :rewards, only: [:new, :create]

  resources :user_challenges, only: [:index, :show, :update] do
    member do
      patch 'toggle_complete'
    end
  end

  resources :user_categories, only: [:index, :show, :new, :create, :destroy]
  get '/edit_user_category', to: 'user_categories#edit', as: 'edit_user_category'
  patch '/user_category', to: 'user_categories#update', as: 'update_user_category'
  resources :categories, only: [:index, :show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many  :user_categories, dependent: :destroy
  has_many  :categories, through: :user_categories
  has_many  :user_challenges, dependent: :destroy
  validates :user_name, presence: true, uniqueness: true
  validates :region, presence: true

  has_many :completed_user_challenges, -> { where(done: true) }, class_name: 'UserChallenge'
  has_many :completed_actions, through: :completed_user_challenges, source: :action

  def total_value_of_completed_actions
    user_challenges.joins(:action)
                      .where(done: true)
                      .sum('actions.value')
  end

  def self.ranked_by_total_value
    joins(user_challenges: :action)
      .where(user_challenges: { done: true })
      .group('users.id')
      .select('users.*, SUM(actions.value) as total_value')
      .order('total_value DESC')
      .limit(10)
  end

  def current_level
    level = total_value_of_completed_actions / 100
    level + 1
  end

  def achieved_action?(action)
    completed_actions = user_challenges.where(action: action, done: true).count
    completed_actions >= 5
  end
  
  def has_completed_actions?
    user_challenges.joins(:action)
                  .where(done: true)
                  .group('actions.id')
                  .having('COUNT(user_challenges.id) >= 5')
                  .exists?
  end
end

app/models/user_category.rb
class UserCategory < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :user_id, presence: true
  validates :category_id, presence: true, uniqueness: { scope: :user_id }
end

app/controllers/user_categories_controller.rb
class UserCategoriesController < ApplicationController

  def index

    @user_categories = UserCategory.where(user_id: current_user.id)

  end

  def show
  end

  def new
    @user = current_user
    @categories = Category.all
    @user_category = UserCategory.new

  end

  def create
    user = current_user
    category_ids = params[:user_category][:category_ids]

    category_ids.each do |category_id|
      user.user_categories.create(category_id: category_id)
    end

    redirect_to home_path
  end

  def edit
    @user = current_user
    @categories = Category.all
    @user_categories = UserCategory.where(user_id: current_user.id)
  end

  def update
    @user_categories = UserCategory.where(user_id: current_user.id)
      @user_categories.each do |user_category|
        user_category.destroy
      end
    category_ids = params[:user_category][:category_ids]
    category_ids.each do |category_id|
      current_user.user_categories.create(category_id: category_id)
    end

    redirect_to actions_path
  end

  def destroy
  end


  private

  def user_category_params
    params.require(:user_category).permit(:user_id, :category_id, category_ids: [])
  end
end

app/views/user_categories/edit.html.erb
<h1 class="fonts-title text-center">Ajuste tes categories </h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <%= simple_form_for([@user_categories, @user], url: update_user_category_path, method: :patch, data: { controller: "hello" }, class: "category_form") do |f| %>

                <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
            <div class="container d-flex">
              <div class="row">

                <% @categories.each do |category| %>
                  <label>
                    <div class="categories  text-center fonts-text">
                     <%# <%= f.input :category_ids, label: "", as: :check_boxes, collection: [[category.title, category.id]], checked: @user.categories.include?(category) %>
                      <% color = category.category_color %>
                      <div class="custom-checkbox" style="--category_checkbox:<%= category.category_color %>;">
                      <%= label_tag "category_#{category.id}", category.title, class: "category_checkbox" %>
                      <%= check_box_tag 'user_category[category_ids][]', category.id, @user.categories.include?(category) %>
                      <%# <%= category.title %>
          </div>
                    </div>
                  </label>
                  <br>
                <% end %>
                  <div class="text-center ">
                    <%= f.submit 'Enregistrer', class:'btn btn-outline-dark categories categories fonts-text'  %>
                  </div>
              </div>
            </div>
      <% end %>
   </div>
  </div>
</div>

app/views/user_categories/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h1 class="text-center">Mes categories selectionnées</h1>
      <%# <div class="col-12 col-md-6"> %>
          <% @user_categories.each do |user_category|%>
        <div class="custom-card text-center">
            <div class="categories fonts-text">
              <%= user_category.category.title %>
            </div>
        </div>
          <%end%>
        </div>
      <%# </div> %>
        <div class="custom-card text-center fonts-text">
          <%= link_to "Ajuster mes categories", edit_user_category_path, class:"btn categories" %>
        </div>
  </div>
</div>

app/views/user_categories/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="categories justify-content">Categories disponibles</h1>
      <p>Choisissez dans quelles categories vous voulez vous investir </p>

        <%= simple_form_for([@user_category, @user], url: user_categories_path, method: :post) do |f| %>

          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
            <div class="container d-flex">
                <div class="row">
                  <% @categories.each do |category| %>
                    <label>
                      <div class="cards">
                        <%= check_box_tag 'user_category[category_ids][]', category.id, @user.categories.include?(category) %>
                        <%= category.title %>
                      </div>
                    </label>
                    <br>
                  <% end %>
                  <div class="card categories">
                    <%= f.submit 'Enregistrer', class:"card categories" %>
                  </div>
                </div>
            </div>
        <% end %>
    </div>
  </div>
</div>

app/views/user_categories/show.html.erb
<h1>UserCategories#show</h1>
<p>Find me in app/views/user_categories/show.html.erb</p>

app/views/user_categories/update.html.erb
<h1>UserCategories#update</h1>
<p>Find me in app/views/user_categories/update.html.erb</p>