config/routes.rb
Rails.application.routes.draw do
  get 'rewards/new'
  get 'rewards/create'
  get 'achievements/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "pages#welcome"
  get 'pages/home', to: 'pages#home', as: 'home'
  get '/pages/welcome', to: 'pages#welcome', as: 'welcome'
  get '/achievements', to: 'achievements#index', as: 'achievements'
  get '/pages/profile', to: 'pages#profile', as: 'profile'
  get '/pages/profil', to: 'pages#profil', as: 'profil'
  get '/redirection', to: 'pages#redirection', as: 'redirection'
  get '/pages/impact', to: 'pages#impact', as: 'impact'
  get '/pages/convertisseur', to: 'pages#convertisseur', as: 'convertisseur'

  resources :actions, only: [:index, :show] do
    post 'add_to_challenges', on: :member
    resources :user_challenges, only: [:create]
  end

  resources :rewards, only: [:new, :create]

  resources :user_challenges, only: [:index, :show, :update] do
    member do
      patch 'toggle_complete'
    end
  end

  resources :user_categories, only: [:index, :show, :new, :create, :destroy]
  get '/edit_user_category', to: 'user_categories#edit', as: 'edit_user_category'
  patch '/user_category', to: 'user_categories#update', as: 'update_user_category'
  resources :categories, only: [:index, :show]
end

app/models/user_challenge.rb
class UserChallenge < ApplicationRecord
  belongs_to :user
  belongs_to :action

  validates :user_id, presence: true
  validates :action_id, presence: true
  validates :done, inclusion: [true, false]

  validate :action_once_per_day, on: :create

  private

  def action_once_per_day
    # if UserChallenge.where(user_id: user_id, action_id: action_id).where("DATE(created_at) = ?", Date.today).exists?
    #   errors.add(:base, "You've already added this challenge today.")
    # elsif UserChallenge.where(user_id: user_id, action_id: action_id, done: false).exists?
    #   errors.add(:base, "You've already added this challenge.")
    # end
  end
end

app/controllers/user_challenges_controller.rb
class UserChallengesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_challenges = current_user.user_challenges.includes(:action)
  end

  def show
    @user_challenge = current_user.user_challenges.find(params[:id])
  end

  def update
  end

  def create
  end

  def toggle_complete
    @user_challenge = UserChallenge.find(params[:id])
    @user_challenge.update(done: !@user_challenge.done, completed_date: Date.today.strftime('%d/%m/%Y'))
    redirect_to user_challenge_path(@user_challenge)
  end

  private

  def user_challenge_params
    params.require(:user_challenge).permit(:done, :completed_date)
  end
end

app/views/user_challenges/destroy.html.erb
<h1>UserChallenges#destroy</h1>
<p>Find me in app/views/user_challenges/destroy.html.erb</p>

app/views/user_challenges/edit.html.erb
<h1>UserChallenges#edit</h1>
<p>Find me in app/views/user_challenges/edit.html.erb</p>

app/views/user_challenges/index.html.erb
<div class="banner">
  <div class="container">
    <h1 class="text-center"><strong>Vos Challenges!</strong></h1>
  </div>
</div>

<div class="custom-container">

  <h2 class="text-center">Challenges en cours</h2>
  <div class="row marge-div">
    <% sorted_user_challenges = @user_challenges.reject { |uc| uc.done }.sort_by { |uc| [uc.action.category.title, uc.action.name] } %>
    <% current_category = nil %>
    <% sorted_user_challenges.each do |user_challenge| %>
      <div class="col-6 cards-action-index">
        <div class="custom-card-custom-action-card" style="border: 3px solid <%= user_challenge.action.category.category_color %>" >
          <div class="custom-card-title" style="background-color: <%= user_challenge.action.category.category_color %>">
            <%= link_to user_challenge_path(user_challenge), class:'link-to-text text-truncate' do %>
              <%= user_challenge.action.name %>
            <% end %>
          </div>
          <% unless user_challenge.done %>
            <div class="custom-card-icon">
              <%= link_to user_challenge_path(user_challenge) do %>
                <%= image_tag("icons/#{user_challenge.action.icon}", alt: 'Icon') %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>


<%# <h2>Completed Challenges</h2>
  <ul class="completed-challenges-list">
    <% current_category = nil %>
    <%# <% @user_challenges.select { |uc| uc.done }.each do |completed_challenge| %>
      <%# <% if completed_challenge.action.category.title != current_category %>
        <%# <% current_category = completed_challenge.action.category.title %>
        <%# <h3><%= current_category</h3> %>
      <%# <% end %>
      <%# <li><%= completed_challenge.action.name %><%#</li> %>
    <%# <% end %>
  <%# </ul> %>
<%# </div> %>

<%# <h2>Completed Challenges</h2> %>
  <%# <ul class="completed-challenges-list"> %>
    <%# <% completed_challenge_counts = Hash.new(0) %>
    <%# <% @user_challenges.select { |uc| uc.done }.each do |completed_challenge| %>
      <%# <% completed_challenge_counts[completed_challenge.action.name] += 1 %>
    <%# <% end %>
    <%# <% completed_challenge_counts.each do |challenge_name, count| %>
      <%# <li><%= "#{challenge_name} (Completed #{count} times)" %><%#</li> %>
    <%# <% end %>
  <%# </ul> %>
<%# </div> %>

app/views/user_challenges/new.html.erb
<h1>UserChallenges#new</h1>
<p>Find me in app/views/user_challenges/new.html.erb</p>

app/views/user_challenges/show.html.erb
<h1>Détails du défi utilisateur</h1>

<p>Action: <%= @user_challenge.action.name %></p>
<p>Challenge en cours: <%= @user_challenge.done ? "Bien joué" : "Vous n'avez pas terminé" %></p>
<p>Date de réalisation: <%= @user_challenge.completed_date %></p>

<% unless @user_challenge.done %>
  <%= button_to "Modifier le statut.", toggle_complete_user_challenge_path(@user_challenge), method: :patch, class:'btn btn-outline-dark categories fonts-text'  %>
<% end %>
<br>
<%= link_to "Retour à vos challenges", user_challenges_path , class:'btn btn-outline-dark categories fonts-text' %>
<br>
<%= link_to "Retour à la page d'accueil", home_path , class:'btn btn-outline-dark categories fonts-text' %>

app/views/user_challenges/update.html.erb
<h1>Mise à jour du défi utilisateur</h1>

<%= form_for(@user_challenge) do |f| %>
  <div class="field">
    <%= f.label :done %>
    <%= f.check_box :done %>
  </div>

  <div class="field">
    <%= f.label :completed_date %>
    <%= f.date_field :completed_date %>
  </div>

  <%= f.submit "Mettre à jour le défi utilisateur" %>
<% end %>

<%= link_to "Retour", user_challenges_path %>