config/routes.rb
Rails.application.routes.draw do
  get 'rewards/new'
  get 'rewards/create'
  get 'achievements/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "pages#welcome"
  get 'pages/home', to: 'pages#home', as: 'home'
  get '/pages/welcome', to: 'pages#welcome', as: 'welcome'
  get '/achievements', to: 'achievements#index', as: 'achievements'
  get '/pages/profile', to: 'pages#profile', as: 'profile'
  get '/pages/profil', to: 'pages#profil', as: 'profil'
  get '/redirection', to: 'pages#redirection', as: 'redirection'
  get '/pages/impact', to: 'pages#impact', as: 'impact'
  get '/pages/convertisseur', to: 'pages#convertisseur', as: 'convertisseur'

  resources :actions, only: [:index, :show] do
    post 'add_to_challenges', on: :member
    resources :user_challenges, only: [:create]
  end

  resources :rewards, only: [:new, :create]

  resources :user_challenges, only: [:index, :show, :update] do
    member do
      patch 'toggle_complete'
    end
  end

  resources :user_categories, only: [:index, :show, :new, :create, :destroy]
  get '/edit_user_category', to: 'user_categories#edit', as: 'edit_user_category'
  patch '/user_category', to: 'user_categories#update', as: 'update_user_category'
  resources :categories, only: [:index, :show]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn categories-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn categories-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/Sam-lewagonsudent/rails-buildup"><i class="fab fa-github"></i></a>
    <a href="https://nosgestesclimat.fr/"><i class="fa-solid fa-leaf"></i></a>
    <a href="https://impactco2.fr/"><i class="fa-solid fa-cloud-arrow-down"></i></a>
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon postion-fixed" data-controller="audios">
  <div class="container-fluid">
    <%= link_to  home_path, class: "navbar-brand" do %>
      <%= image_tag "buildup.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-audios-target="elem" data-action='click->audios#playSound' data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto nav-link">
        <% if user_signed_in? %>
          <li class="nav-item active " data-audios-target="elem" data-action='click->audios#playSound'>
            <%= link_to "Profil", profil_path, class: "nav-link fonts-nav"%>
          </li>
          <li class="nav-item active " data-audios-target="elem" data-action='click->audios#playSound'>
            <%= link_to "Home", home_path, class: "nav-link fonts-nav" %>
          </li>
          <li class="nav-item active " data-audios-target="elem" data-action='click->audios#playSound'>
            <%= link_to "Liste des actions disponible", actions_path, class: "nav-link fonts-nav" %>
          </li>
          <li class="nav-item active " data-audios-target="elem" data-action='click->audios#playSound'>
            <%= link_to "Liste de vos challenges", user_challenges_path, class: "nav-link fonts-nav" %>
          </li>
          <li class="nav-item active " data-audios-target="elem" data-action='click->audios#playSound'>
            <%= link_to "Log out",  destroy_user_session_path,data: {turbo_method: :delete}, class: "nav-link fonts-nav" %>
          </li>
        <% else %>
          <li class="nav-item inline">
            <%= link_to 'Inscription', new_user_registration_path, data: { audios_target: "elem", action: "click->audios#playSound" }, class: "nav-link"%>
          </li>
          <li class="nav-item inline">
            <%= link_to 'Connexion', new_user_session_path, data: { audios_target: "elem", action: "click->audios#playSound" },  class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<nav class="mobile-nav box">
        <%# <a href="#" class="bloc-icon">
            <img src="./home.png" alt="npa">
        </a>%>
            <%= link_to home_path, class:"bloc-icon" do%>
             <%= image_tag "home.png"%>
              <% end %>

        <%# <a href="#" class="bloc-icon">
            <img src="search.png" alt="">
        </a> %>
         <%= link_to actions_path, class:"bloc-icon" do %>
          <%= image_tag "search.png"%>
           <% end %>

        <%# <a href="#" class="bloc-icon">
            <img src="leaf.png" alt="">
        </a> %>
         <%= link_to  user_challenges_path, class:"bloc-icon" do %>
          <%= image_tag "leaf.png"%>
           <% end %>

        <%# <a href="#" class="bloc-icon">
            <img src="user.png" alt="">
        </a> %>
         <%= link_to  profil_path,  class:"bloc-icon" do%>
          <%= image_tag "user.png"%>
           <% end %>

        <%# <a href="#" class="bloc-icon">
            <img src="ressources/user.svg" alt="">
        </a> %>

    </nav>