config/routes.rb
Rails.application.routes.draw do
  get 'rewards/new'
  get 'rewards/create'
  get 'achievements/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: "pages#welcome"
  get 'pages/home', to: 'pages#home', as: 'home'
  get '/pages/welcome', to: 'pages#welcome', as: 'welcome'
  get '/achievements', to: 'achievements#index', as: 'achievements'
  get '/pages/profile', to: 'pages#profile', as: 'profile'
  get '/pages/profil', to: 'pages#profil', as: 'profil'
  get '/redirection', to: 'pages#redirection', as: 'redirection'
  get '/pages/impact', to: 'pages#impact', as: 'impact'
  get '/pages/convertisseur', to: 'pages#convertisseur', as: 'convertisseur'

  resources :actions, only: [:index, :show] do
    post 'add_to_challenges', on: :member
    resources :user_challenges, only: [:create]
  end

  resources :rewards, only: [:new, :create]

  resources :user_challenges, only: [:index, :show, :update] do
    member do
      patch 'toggle_complete'
    end
  end

  resources :user_categories, only: [:index, :show, :new, :create, :destroy]
  get '/edit_user_category', to: 'user_categories#edit', as: 'edit_user_category'
  patch '/user_category', to: 'user_categories#update', as: 'update_user_category'
  resources :categories, only: [:index, :show]
end

app/views/pages/bootstrap.html.erb
    <% @user_categories.each do |user_category|%>
<div class="container">
  <ul class="ks-cboxtags">
  <li>
        <input type="checkbox",id= "checkbox<%=user_category.category.title%>",  value="<%= user_category.category.title %>">
          <label for="checkbox<%=user_category.category.title%>">
              <%= user_category.category.title %>
          </label>
      </li>
    <%# <li><input type="checkbox",id= "checkboxOne",  value="Rainbow Dash">Rainbow Dash<label for="checkboxOne"></label></li>
    <li><input type="checkbox" id="checkboxTwo" value="Cotton Candy" checked><label for="checkboxTwo">Cotton Candy</label></li>
    <li><input type="checkbox" id="checkboxThree" value="Rarity" checked><label for="checkboxThree">Rarity</label></li>
    <li><input type="checkbox" id="checkboxFour" value="Moondancer"><label for="checkboxFour">Moondancer</label></li>
    <li><input type="checkbox" id="checkboxFive" value="Surprise"><label for="checkboxFive">Surprise</label></li>
    <li><input type="checkbox" id="checkboxSix" value="Twilight Sparkle" checked><label for="checkboxSix">Twilight
                    Sparkle</label></li>
    <li><input type="checkbox" id="checkboxSeven" value="Fluttershy"><label for="checkboxSeven">Fluttershy</label></li>
    <li><input type="checkbox" id="checkboxEight" value="Derpy Hooves"><label for="checkboxEight">Derpy Hooves</label></li>
    <li><input type="checkbox" id="checkboxNine" value="Princess Celestia"><label for="checkboxNine">Princess
                    Celestia</label></li>
    <li><input type="checkbox" id="checkboxTen" value="Gusty"><label for="checkboxTen">Gusty</label></li>
    <li class="ks-selected"><input type="checkbox" id="checkboxEleven" value="Discord"><label for="checkboxEleven">Discord</label></li>
    <li><input type="checkbox" id="checkboxTwelve" value="Clover"><label for="checkboxTwelve">Clover</label></li>
    <li><input type="checkbox" id="checkboxThirteen" value="Baby Moondancer"><label for="checkboxThirteen">Baby
                    Moondancer</label></li>
    <li><input type="checkbox" id="checkboxFourteen" value="Medley"><label for="checkboxFourteen">Medley</label></li>
    <li><input type="checkbox" id="checkboxFifteen" value="Firefly"><label for="checkboxFifteen">Firefly</label></li> %>
  </ul>
</div>
 <%end%>

app/views/pages/convertisseur.html.erb
<head>
<title>Convertisseur de points</title>
<%# <meta charset="utf-8"> %>
<link rel="stylesheet" href="ex.scss">
<script src="convertisseur.js" async></script>
</head>

 <h2>Convertisseur de points:</h2>
 <div class="">

            <label>points</label>
            <input  id="points" type="number" placeholder="points">


            <label>grCO2</label>
            <input   id="grCO2" type="number" placeholder="grCO2">


            <label>KgCO2</label>
            <input   id="KgCO2" type="number" placeholder="KgCO2">
       
</div>

<%# <%= simple_form_for @model do |f| %>
  <%# <%= f.input :points, label: "Points", input_html: { id: "points", type: "number", placeholder: "points" } %>
  <%# <%= f.input :grCO2, label: "Grammes de CO2", input_html: { id: "grCO2", type: "number", placeholder: "grCO2" } %>
  <%# <%= f.input :KgCO2, label: "Kilogrammes de CO2", input_html: { id: "KgCO2", type: "number", placeholder: "KgCO2" } %>
<%# <% end %>

app/views/pages/home.html.erb
<div class="home-profile">
  <% if current_user.nil? %>
    <div class="banner">
      <div class="row justify-content-center">
        <p class="welcome-text"></p>
        <%= image_tag "BuildUp2.png", class:"logo-large" %>
      </div>
      <%= link_to "connexion", new_user_session_path, class:'btn ' %>
      <%= link_to "inscription", user_session_path, class:'btn ' %>
    </div>
  <% else %>

  <div class="d-flex flex-column align-items-center user-header">
    <div class="d-flex align-items-center">
      <h2 class="mr-3">Salut, <%= current_user.user_name %>!</h2>
      <% if current_user.selected_icon.present? %>
        <div class="avatar-list mx-auto">
          <div class="avatar avatar-x-large-home">
            <%= image_tag("achievements/#{current_user.selected_icon}", alt: "Usuário", class: "avatar-image") %>
            <img src="" class="avatar-frame anim-hue">
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="container">
    <div class="bar-margin">
      <div class="progress-bar">
        <div class="progress" style="width: <%= @user_progress %>%;"> </div>
      </div>
      <p>Level: <%= @user_level %></p>
      <p>Total de vos points: <%= @total_value %></p>
    </div>
  </div>

  <div class="container">
    <div class="row mb-3">
      <div class="scrolling-wrapper">
        <% sorted_user_challenges = @user_challenges.reject { |uc| uc.done }.sort_by { |uc| [uc.action.category.title, uc.action.name] } %>
        <% current_category = nil %>
        <% sorted_user_challenges.each do |user_challenge| %>
          <div class="col-6 cards-action-index">
            <div class="home-card" style="border: 3px solid <%= user_challenge.action.category.category_color %>">
              <div class="custom-card-title" style="background-color: <%= user_challenge.action.category.category_color %>">
                <%= link_to user_challenge_path(user_challenge), class:'link-to-text text-truncate' do %>
                  <%= user_challenge.action.name %>
                <% end %>
              </div>
              <% unless user_challenge.done %>
                <div class="custom-card-icon ">
                  <%= link_to user_challenge_path(user_challenge) do %>
                    <%= image_tag("icons/#{user_challenge.action.icon}", class:"home-card-icon", alt: 'Icon') %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container">
    <button class="btn border-top text-start d-flex justify-content-around " type="button" data-bs-toggle="collapse" data-bs-target="#collapseHome" aria-expanded="false" aria-controls="collapseHome">
      Classement des utilisateurs par actions complétées.<%= image_tag "collapsedown.png", class:"litlle-icon "%>
    </button>
    <div class="collapse" id="collapseHome">
      <div class="categories fonts-text">
        <% @ranked_users.each_with_index do |user, index| %>
          <div class="custom-card text-center">
            <%= index + 1 %>. <%= user.user_name %> - Valeur total: <%= user.total_value %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container">
    <button class="btn border-top text-start d-flex justify-content-around" type="button" data-bs-toggle="collapse" data-bs-target="#collapseHome1" aria-expanded="false" aria-controls="collapseHome1">
      Classement des utilisateurs par catégories.<%= image_tag "collapsedown.png", class:"litlle-icon"%>
    </button>
    <div class="collapse" id="collapseHome1">
      <div class="categories fonts-text">
        <% @ranked_categories.each_with_index do |category, index| %>
          <p>
            <%= index + 1 %>. <%= category.title %> - Valeur total: <%= category.total_value %>
          </p>
          <p>
            Total d'equivalent CO2 economisé: <%= category.total_value / 0.01 %> grCO2
          </p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="container">
    <button class="btn border-top text-start d-flex justify-content-around" type="button" data-bs-toggle="collapse" data-bs-target="#collapseHome2" aria-expanded="false" aria-controls="collapseHome2">
      Classement utilisateurs des actions complétées par catégories.<%= image_tag "collapsedown.png", class:"litlle-icon"%>
    </button>
    <div class="collapse" id="collapseHome2">
      <div class="categories fonts-text">
        <% @categories.each do |category| %>
          <h5><%= category.title %></h5>
          <% category.ranked_users_by_total_value.each_with_index do |user, index| %>
            <p class="text-truncate">
              <%= index + 1 %>. <%= user.user_name %> - Valeur total: <%= user.total_value %>
            </p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <% end %>
</div>

app/views/pages/impact.html.erb
<script id="datagir-impact-co2" src="https://impactco2.fr/iframe.js" data-type="numerique" data-search="?theme=default"></script>

app/views/pages/profil.html.erb
<div class="d-flex flex-column user-header">
  <div class="d-flex align-items-center">
    <h2 class="mr-3 text-start"><%= current_user.user_name %></h2>

    <% if current_user.selected_icon.present? %>
    <div class="avatar-list">
      <div class="avatar avatar-x-large-home">
        <%= image_tag("achievements/#{current_user.selected_icon}", alt: "Usuário", class: "avatar-image") %>
        <img src="" class="avatar-frame anim-hue">
      </div>
    </div>
    <% end %>
  </div>
</div>
<div class="bar-margin">
  <div class="progress-bar">
    <div class="progress" style="width: <%= @user_progress %>%;"></div>
  </div>
  <p>Level: <%= @user_level %></p>
  <p>Total de vos points: <%= @total_value %></p>
</div>
<div class="mb-2 container">
  <button class="btn border-top text-start d-flex justify-content-around" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Mes categories déjà selectionnées <%= image_tag "collapsedown.png", class:"litlle-icon"%>
  </button>
  <div class="collapse" id="collapseExample">
    <div class="categories fonts-text">
      <% @user_categories.each do |user_category|%>
      <div class="custom-card text-center" style="background-color:<%= user_category.category.category_color %>">
        <div class="categories fonts-text">
          <%= user_category.category.title %>
        </div>
      </div>
      <% end %>
      <div class="custom-card text-center fonts-text">
        <%= link_to "Ajuster la selection", edit_user_category_path, class:"btn btn-custom categories " %>
      </div>
    </div>
  </div>
</div>
</div>
</div>

<div class="mb-5 text-center">
  <h2>Challenges terminés</h2>
</div>
<div class="completed-challenges-list">
  <% completed_challenge_counts = Hash.new(0) %>
  <% completed_categories = Set.new %>
  <% @user_challenges.select { |uc| uc.done }.each do |completed_challenge| %>
  <% challenge_name = completed_challenge.action.name %>
  <% completed_challenge_counts[challenge_name] += 1 %>
  <% completed_categories.add(completed_challenge.action.category.title.downcase.gsub(' ', '_')) %>
  <% end %>
</div>

<div class=" container">
    <% completed_categories.each do |category| %>
        <% category_display = category.gsub('_', ' ').titleize %>
            <button class="btn border-top text-start d-flex justify-content-between" type="button" data-bs-toggle="collapse" data-bs-target="#collapse<%=category%>" aria-expanded="false" aria-controls="collapse<%=category%>">
            <%= category_display %><%= image_tag "collapsedown.png", class:"litlle-icon"%>
          </button>
          <div class="collapse" id="collapse<%=category%>">
            <div class="categories fonts-text">
              <ul>
                <% @user_challenges.select { |uc| uc.done && uc.action.category.title.downcase.gsub(' ', '_') == category }.each do |completed_challenge| %>
                  <% challenge_name = completed_challenge.action.name %>
                  <% if completed_challenge_counts[challenge_name] > 0 %>
                    <li><%= "#{challenge_name} (Complété #{completed_challenge_counts[challenge_name]} fois)" %></li>
                    <% completed_challenge_counts[challenge_name] = 0 %>
                  <% end %>
                <% end %>
              </ul>
            </div>
          </div>
    <% end %>


<div class=" container border-top ">
    <div class=" mt-3 mb-3 d-flex justify-content-center"></div>
      <%= link_to "Succès", achievements_path, class:'btn btn-outline-dark categories fonts-text' %>
    </div>
    <div class="mt-3 btn-left">
      <%= link_to "Déconnexion",  destroy_user_session_path,data: {turbo_method: :delete}, class:'btn btn btn-outline-dark categories fonts-text ' %>

    </div>
</div>

app/views/pages/profile.html.erb
<div class="d-flex flex-column align-items-center user-header">
  <div class="d-flex align-items-left">
    <h2 class="mr-3"><%= current_user.user_name %></h2>

    <% if current_user.selected_icon.present? %>
      <div class="selected-icon">
        <%= image_tag("achievements/#{current_user.selected_icon}", alt: "Selected Icon", width: 50, height: 50, class: "img-fluid") %>
      </div>
    <% end %>
  </div>
</div>
<%= link_to "Achievements", achievements_path, class:'btn btn-outline-dark categories ' %>

<div class="col-md-4">
  <a class="btn btn-primary" data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Mes categories selectionnées
  </a>

  <div id="panelsStayOpen-collapseTwo-1" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo-1">
    <div class="accordion-body">
      <div class="card-body text-center d-flex justify-content-start">
        <% @user_categories.each do |user_category| %>
          <div class="custom-card text-center">
            <div class="categories fonts-text">
              <%= user_category.category.title %>
            </div>
          </div>
        <% end %>

        <div class="custom-card text-center fonts-text">
          <%= link_to "Ajuster mes categories", edit_user_category_path, class:"btn btn-custom categories " %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="col-md-4">
  <div class="accordion custom-card align-items-start" id="accordionPanelsStayOpenprofil3">
    <div class="accordion-item">
      <h2 class="accordion-header" id="panelsStayOpen-headingOne-profil-3">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne-3" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne-3">
          Challenge du jour
        </button>
      </h2>
      <div id="panelsStayOpen-collapseOne-3" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne-3">
        <div class="accordion-body">
          <div class="card-body text-center d-flex justify-content-start">
            <% @completed_chal_historic.each do |user_challenge| %>
              <p class="card-text d-flex">
                Challenge: <%= user_challenge.done %>
                Date: <%= user_challenge.created_at %>
                action: <%= user_challenge.action.name %>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<h2>Challenges terminés</h2>
<div class="completed-challenges-list">
  <% completed_challenge_counts = Hash.new(0) %>
  <% completed_categories = Set.new %>
  <% @user_challenges.select { |uc| uc.done }.each do |completed_challenge| %>
    <% challenge_name = completed_challenge.action.name %>
    <% completed_challenge_counts[challenge_name] += 1 %>
    <% completed_categories.add(completed_challenge.action.category.title.downcase.gsub(' ', '_')) %>
  <% end %>

  <div class="custom-card-uc" id="accordionPanelsStayOpenExample1">
    <% completed_categories.each do |category| %>
      <div class="accordion-item1">
        <% category_display = category.gsub('_', ' ').titleize %>
        <h3 class="accordion-header" id="panelsStayOpen-headingOne-<%= category %>">
          <button class="accordion-button1" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne-<%= category %>" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne-<%= category %>">
            <%= category_display %>
          </button>
        </h3>
        <div id="panelsStayOpen-collapseOne-<%= category %>" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingOne-<%= category %>" data-bs-parent="#accordionPanelsStayOpenExample1">
          <div class="accordion-body">
            <div class="card-body text-center d-flex justify-content-start">
              <ul>
                <% @user_challenges.select { |uc| uc.done && uc.action.category.title.downcase.gsub(' ', '_') == category }.each do |completed_challenge| %>
                  <% challenge_name = completed_challenge.action.name %>
                  <% if completed_challenge_counts[challenge_name] > 0 %>
                    <li><%= "#{challenge_name} (Completed #{completed_challenge_counts[challenge_name]} times)" %></li>
                    <% completed_challenge_counts[challenge_name] = 0 %>
                  <% end %>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

      <%# <div class="col-md-4">
        <div class="accordion custom-card align-items-start" id="accordionPanelsStayOpenprofil2">
          <div class="accordion-item">
            <h2 class="accordion-header" id="panelsStayOpen-headingOne-profil-2">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne-2" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne-2">
              Categorie
              </button>
            </h2>


                  <div id="panelsStayOpen-collapseOne-2" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne-2">
                    <div class="accordion-body">
                      <div class="card-body text-center d-flex justify-content-start">
                        <% @completed_chal_historic.each do |user_challenge| %>
                          <%# <p class="card-text d-flex">
                            Challenge: <%= user_challenge.done %>
                            <%# Date: <%= user_challenge.created_at %>
                            <%# action: <%= user_challenge.action.name %>
                          <%# </p>
                        <% end %>
                      <%# </div>
                    </div>
                  </div>
            </div>
          </div>
      </div>%>

<%# <p>
  <h1 class="text-center"> Historique des challenges </h1>
  </p>
<div class="container mt-5">
  <div class="d-flex justify-content-center">
      <div>
        <% @completed_chal_historic.each do |user_challenge| %>
          <%# <p>
            Challenge: <%= user_challenge.done %>
            <%# Date: <%= user_challenge.created_at %>
            <%# action: <%= user_challenge.action.name %>
          <%# </p>
        <% end %>
      <%# </div> %>
  <%# </div> %>

app/views/pages/welcome.html.erb
<div class="home-profile">
  <% if current_user.nil? %>
    <div class="banner" >
          <div class="row justify-content-center">
            <p class="welcome-text">
            </p>
            <%= image_tag "BuildUp2.png", class:"logo-large" %>
          </div>
          <%= link_to "connexion",  new_user_session_path, class:'btn ' %>
          <%= link_to "inscription", user_session_path, class:'btn ' %>
    </div>
  <% else %>
    <div class="banner" >
          <div class="row justify-content-center">
            <p class="welcome-text">
            </p>
            <%= image_tag "BuildUp2.png", class:"logo-large" %>
          </div>
    </div>
  <% end %>
</div>